### ISSUE TITLE
I am a bit confused, do the wherez have a static port? what is being advertised?

### ISSUE THREAD

**Issue by elico** [nictuku/wherez#4]
I was reading the code and I have seen the example but I am unsure if I understood correctly.
The wherez service listens on one port and the service is in another, right?
Then the wherez advertises it's service which is on let say port 8080?

Thanks,

**Comment by nictuku** [comment]
Yes, you're right. Wherez itself listens on port 40000 by default:

https://github.com/nictuku/wherez/blob/master/wherez/wherez.go#L13

Hope this helps.

**Comment by elico** [comment]
Thanks!
